# https://akahana-1.hatenablog.jp/entry/2017/11/07/153741
# https://memo.geso.site/entry/2024/01/18/205813
set-option -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256col*:Tc"

# Change prefix key
set -g prefix C-q
unbind C-b

# Mouse scroll.
set -g mouse on
bind-key -T copy-mode WheelUpPane send-keys -X -N 1 scroll-up
bind-key -T copy-mode WheelDownPane send-keys -X -N 1 scroll-down

set -g pane-border-lines heavy
set -g pane-border-indicators both
