set-option default-terminal "screen-256color"

# Change prefix key
set -g prefix C-q
unbind C-b

# Mouse scroll.
set -g mouse on
bind-key -T copy-mode WheelUpPane send-keys -X -N 1 scroll-up
bind-key -T copy-mode WheelDownPane send-keys -X -N 1 scroll-down

set -g pane-border-lines heavy
set -g pane-border-indicators both

set -g cursor-style blinking-block
