# brew "awscli"
brew "direnv"
brew "tree"
brew "wget"
brew "git"
brew "zsh"
brew "peco"
brew "redpen"
brew "rust"
brew "protobuf"
brew "golang"

# brew "cmake"
# brew "gcc"
# brew "libomp"

cask "alfred"
cask "discord"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "skim"
cask "visual-studio-code"
# cask "minikube"

# Google Chrome is pre-installed in some environment.
# cask "google-chrome"
