# brew "awscli"
brew "asdf"
brew "cloud-sql-proxy"
brew "direnv"
brew "git"
brew "golang"
brew "peco"
brew "protobuf"
brew "postgresql"
brew "rust"
brew "sqlc"
brew "tree"
brew "tmux"
brew "wget"
brew "zsh"

# Required to build emacs
brew "libgccjit"
brew "texinfo"
brew "gnutls"
brew "autoconf"

brew "hashicorp/tap/terraform-ls"

# brew "cmake"
# brew "gcc"
# brew "libomp"

cask "alfred"
cask "discord"
cask "ghostty"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "iterm2"
cask "karabiner-elements"
cask "visual-studio-code"
