# brew "awscli"
brew "asdf"
brew "direnv"
brew "git"
brew "golang"
brew "peco"
brew "poetry"
brew "protobuf"
brew "postgresql"
brew "redpen"
brew "rust"
brew "sl"
brew "sqlc"
brew "tree"
brew "wget"
brew "zsh"

# brew "cmake"
# brew "gcc"
# brew "libomp"

cask "alfred"
cask "discord"
cask "docker"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "skim"
cask "visual-studio-code"

tap "railwaycat/emacsmacport"
cask "emacs-mac"
