version: 2

jobs:

  test_make_commands:
    working_directory: ~/dotfiles
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: create symbolic links
          command: make symbolic-links

workflows:
  version: 2
  tests:
    jobs:
      - test_make_commands
