[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/solarized_dark.toml"
]

[window]
opacity = 0.85
# decorations = "None"
dynamic_padding = true
decorations_theme_variant = "None"

[window.padding]
x = 8
y = 4

[window.dimensions]
columns = 120
lines = 30

[keyboard]
bindings = [
    { "key" = "F11", "action" = "ToggleFullscreen" }
]

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Block"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "HackGen Console NF", style = "Regular" }
bold = { family = "HackGen Console NF", style = "Bold" }
italic = { family = "HackGen Console NF", style = "Italic" }
bold_italic = { family = "HackGen Console NF", style = "Bold Italic" }
size = 24
offset = { x = 0, y = 2 }

[env]
TERM = "tmux-256color"
