name: Mac

on: [push]

jobs:

  mac:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install packages via Homebrew
        run: brew bundle install
